# Dockerfile di test per radon-defuse
FROM ubuntu:latest

# Esecuzione di comandi come root senza pulizia della cachedwdwq
RUN apt-get update && apt-get install -y curl vim git

# Esposizione porta standard
EXPOSE 8080

CMD ["bash"]
