on: [push]

jobs:
  defect_prediction_job:
    runs-on: ubuntu-latest
    name: Run DEFUSE's model for Terraform
    steps:
      - name: Defect Prediction
        id: defect_prediction
        uses: sighzeero/EQS-radon-defuse-action@v1.0.6
        with:
          model: 'gleWeNXLiV32WX3tlNLD' # <-- SOSTITUISCI con l'ID copiato da Defuse
          language: 'terraform'              # <-- CAMBIATO da 'ansible' a 'terraform'
          url: 'https://gauzy-virgie-timbreled.ngrok-free.dev' # <-- SOSTITUISCI con il tuo URL Ngrok attivo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
